### ISSUE TITLE
*** error: Index name 'index_taggings_on_tag_id' on table 'taggings' already exists

### ISSUE THREAD

**Issue by randomm** [openfootball/datafile#1]
Hi, I'm trying to use the sportdb tool to get an English database set up, however, I keep running into this error:

    *** error: Index name 'index_taggings_on_tag_id' on table 'taggings' already exists

This happens with the new command, as well as create command.

(this is possibly a sportdb issue, not a datafile issue per se ... apologies in that case!)

**Comment by geraldb** [comment]
@randomm Please post questions and comments to the forum / mailing list.  This is a known issue - for now sorry - the ActiveRecord 5.x series doesnt work yet. Cheers.

**Comment by softcomet** [comment]
@geraldb 
I have same issue still. I am not sure whether this issue has been fixed for now or not.
